DBHOST          ='localhost'
DBNAME          ='news'
DBPORT          = 3306
DBUSER          = 'news'
DBPWD           = 'WImGfKxkx2CQ0B9'
DBTBB           = 'blackboard'
DBTSTOP         = 'stop'
DBTMELDUNGEN    = 'meldungen'  #unbearbetete Meldungen
DBTDATEN        ='daten'            #bearbeitete Meldungen