DBHOST          ='localhost'
DBNAME          ='news'
DBPORT          = 3306
DBUSER          = 'news'
DBPWD           = 'WImGfKxkx2CQ0B9'
DBTBB           = 'blackboard'
DBTSTOP         = 'stop'
DBTMELDUNGEN    = 'meldungen'  #unbearbetete Meldungen
DBTDATEN        ='daten'       #bearbeitete Meldungen
DBTW1           ='woerter1'    
DBTW2           ='woerter2'    
DBTW3           ='woerter3'    
DBTW4           ='woerter4'    
DBTW5           ='woerter5'    
DBTW6           ='woerter6'    