DBHOST = "localhost"
DBNAME = "news"
DBPORT = 3306
DBUSER = "news"
DBPWD = "news"
DBTBB = "blackboard"
DBTSTOP = "stop"
DBTMELDUNGEN = "meldungen"  # unbearbeitete Meldungen
DBTDATEN = "daten"  # bearbeitete Meldungen
DBTW1 = "woerter1"
DBTW2 = "woerter2"
DBTW3 = "woerter3"
DBTW4 = "woerter4"
DBTW5 = "woerter5"
DBTW6 = "woerter6"
